language: cpp
compiler: gcc
env:
  - PLATFORM=linux
  - PLATFORM=android
matrix:
  allow_failures:
    - env: PLATFORM=android
install:
  - chmod 0755 tools/travis/install.sh
  - tools/travis/install.sh
script:
  - chmod 0755 tools/travis/script.sh
  - tools/travis/script.sh
